Linting AND prettier test

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -5,7 +5,7 @@ on:
   pull_request:
     branches:
       - master
-        
+
 permissions:
   pull-requests: write
 
@@ -27,27 +27,33 @@ jobs:
       - name: Run Linting and Check Results
         id: lint
         run: |
-          npm run lint > lint-output.txt || true
+          npm run lint > lint-output.txt || LINT_EXIT_CODE=$?
           # Count errors and warnings
           ERRORS=$(grep -i "error" lint-output.txt | wc -l)
+          WARNINGS=$(grep -i "warning" lint-output.txt | wc -l)
           echo "errors=$ERRORS" >> $GITHUB_ENV
+          echo "warnings=$WARNINGS" >> $GITHUB_ENV
           cat lint-output.txt
+          # Exit with the original lint exit code if there are errors
+          if [ "$ERRORS" -ne "0" ]; then
+            exit $LINT_EXIT_CODE
+          fi
 
       - name: Add GIF to PR comment
-        if: env.errors != '0'
+        if: env.errors != '0' || env.warnings != '0'
         uses: actions/github-script@v6
         with:
           script: |
             const commentBody = `
-              Linting detected errors 😱😱😱:
+              Linting detected issues 😱😱😱:
             
               - **Errors**: ${process.env.errors}
+              - **Warnings**: ${process.env.warnings}
             
-              ![GIF](https://i.imgur.com/qW7lWJF.gif)
+              ![GIF](https://imgur.com/qW7lWJF)
             `;
             await github.rest.issues.createComment({
               ...context.repo,
               issue_number: context.issue.number,
               body: commentBody,
             });
-
